### ISSUE TITLE
async

### ISSUE THREAD

**Issue by Corn3333** [arlanca/arbitrum-claim#10]
https://github.com/arlanca/arbitrum-claim/blob/7a60789b2b2403943f578c52fa88dbcf522fe23e/src/utils.rs#L10

Что скажешь, если асинхронно запустить в 3-4 потока функцию, но с разным интервалом, к примеру 500 мс?
А то в одном потоке слишком долго.

**Comment by arlanca** [comment]
В многопоточном режиме возможны проблемы с публичными нодами в т.ч рейт лимит, а интервал в 500 мс это около 2 блоков арбитрума, что достаточно много.

**Comment by arlanca** [comment]
В sleep заложено примерное время получения ответа от ноды + создание нового блока(≈250мс).

250мс - 100мс(ожидание)= 150 мс. Примерно такое время я ожидаю от estimateGas на публичных нодах в момент клейма.

**Comment by Corn3333** [comment]
Все будет зависеть от момента, когда будет запущен скрипт. По сути рандом.
Если повезет запустить через долю миллисекунд ПОСЛЕ нового блока, то мы идеально получим следующий блок, а если незадолго ДО нового блока, то узнаем о следующем блоке аккурат перед его завершением.

В среднем, лимиты у нод около 60 запросов в секунду, но больше роляет вес запроса. 
Интервал условный, его можно подобрать.
