### ISSUE TITLE
Случайный газ

### ISSUE THREAD

**Issue by Malenford** [arlanca/arbitrum-claim#9]
Задать для каждого аккаунта случайный газ бид может?
n + рандом 0.1-3 - вроде того

**Comment by arlanca** [comment]
А какое в этом применение?

**Comment by Malenford** [comment]
Плюс к анонимности кошельков, арбитрум то уже вряд ли посмотрит, но какие-нибудь сыщики с проектов типа hop могут потом цепляться к мелочам.
